routes/web.php
<?php

use App\Http\Controllers\Admin;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::view('/', 'home')->name('home');
Route::view('/about', 'about')->name('about');
Route::view('/resume', 'resume')->name('resume');
Route::view('/skills', 'skills')->name('skills');
Route::view('/contact', 'contact')->name('contact');

Route::prefix('admin')->name('admin.')->group(function () {
    Route::middleware('guest')->group(function () {
        Route::get('/login', [Admin\AuthController::class, 'login'])->name('login');
        Route::post('/login', [Admin\AuthController::class, 'authenticate']);
    });

    Route::middleware('auth')->group(function () {
        Route::get('/logout', [Admin\AuthController::class, 'logout'])->name('logout');
        Route::get('/', [Admin\ProfileController::class, 'index'])->name('home');
        Route::post('/', [Admin\ProfileController::class, 'save']);
        Route::post('/social-media', [Admin\ProfileController::class, 'socmed'])->name('socmed');
        Route::post('/skills', [Admin\ProfileController::class, 'skills'])->name('skills');
        Route::get('/resume', [Admin\ResumeController::class, 'index'])->name('resume');
        Route::get('/inbox', [Admin\InboxController::class, 'index'])->name('inbox');
        Route::get('/inbox/{id}', [Admin\InboxController::class, 'show'])->name('inbox.show');
    });
});

resources/views/admin/inbox.blade.php
@extends('admin.layout.base')

@section('content')
    <div class="flex flex-wrap -mx-3">
        <div class="flex-none w-full max-w-full px-3">
            <div class="relative flex flex-col min-w-0 mt-6 mb-6 break-words bg-white border-0 border-transparent border-solid shadow-soft-xl rounded-2xl bg-clip-border">
                <div class="flex-auto px-0 pt-0 pb-2">
                    <div class="p-0 overflow-x-auto">
                        <table class="table-clickable items-center w-full border-collapse mb-0 align-top border-gray-200 text-slate-500">
                            <thead class="align-bottom">
                            <tr>
                                <th class="px-6 py-3 font-bold text-left uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-xxs border-b-solid tracking-none whitespace-nowrap text-slate-400 opacity-70">Name</th>
                                <th class="px-6 py-3 font-bold text-center uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-xxs border-b-solid tracking-none whitespace-nowrap text-slate-400 opacity-70">Subject</th>
                                <th class="px-6 py-3 font-bold text-center uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-xxs border-b-solid tracking-none whitespace-nowrap text-slate-400 opacity-70">Date</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($messages as $message)
                                <tr class="{{ $message->is_read ? '' : 'bg-blue-50' }} hover:bg-blue-50 cursor-pointer border-y-4 border-white" data-href="{{ route('admin.inbox.show', $message->id) }}">
                                    <td class="p-2 align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                                        <h6 class="mb-0 text-sm leading-normal">{{ $message->name }}</h6>
                                        <p class="mb-0 text-xs leading-tight text-slate-400">{{ $message->email }}</p>
                                    </td>
                                    <td class="p-2 align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">{{ $message->subject }}</td>
                                    <td class="p-2 text-center align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">{{ $message->created_at }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <div class="w-full p-3">
                            {{ $messages->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        const tableRows = document.querySelectorAll(".table-clickable tbody tr");

        for (const tableRow of tableRows) {
            tableRow.addEventListener("click", function () {
                // window.open(this.dataset.href, "_blank");
                window.location.href = this.dataset.href;
            });
        }
    </script>
@endpush

resources/views/admin/inbox_show.blade.php
@extends('admin.layout.base')

@section('content')
    <div class="flex flex-wrap -mx-3">
        <div class="flex-none w-full max-w-full px-3">
            <div class="relative flex flex-col min-w-0 p-6 mt-6 mb-6 break-words bg-white border-0 border-transparent border-solid shadow-soft-xl rounded-2xl bg-clip-border">
                <h4>{{ $message->subject }}</h4>
                <p>
                    <span class="font-semibold">{{ $message->name }}</span>
                    <span class="text-sm">{{ '<' . $message->name . '>' }}</span>
                </p>
                <p class="mt-5">{{ $message->message }}</p>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/login.blade.php
<!--
=========================================================
* Soft UI Dashboard Tailwind - v1.0.5
=========================================================

* Product Page: https://www.creative-tim.com/product/soft-ui-dashboard-tailwind
* Copyright 2023 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://www.creative-tim.com/license)
* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="apple-touch-icon" sizes="76x76" href="{{ asset('img/admin/apple-icon.png') }}"/>
    <link rel="icon" type="image/png" href="{{ asset('img/admin/favicon.png') }}"/>
    <title>Soft UI Dashboard Tailwind</title>
    <!-- Fonts and icons -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <!-- Main Styling -->
    @vite(['resources/css/admin.css'])
</head>

<body class="m-0 font-sans antialiased font-normal bg-white text-start text-base leading-default text-slate-500">
    <main class="mt-0 transition-all duration-200 ease-soft-in-out h-full">
        <section>
            <div class="relative flex items-center p-0 overflow-hidden bg-center bg-cover min-h-75-screen">
                <div class="container z-10">
                    <div class="flex flex-wrap mt-0 -mx-3">
                        <div class="flex flex-col w-full max-w-full px-3 mx-auto md:flex-0 shrink-0 md:w-6/12 lg:w-5/12 xl:w-4/12">
                            <div class="relative flex flex-col min-w-0 mt-32 break-words bg-transparent border-0 shadow-none rounded-2xl bg-clip-border">
                                <div class="p-6 pb-0 mb-0 bg-transparent border-b-0 rounded-t-2xl">
                                    <h3 class="relative z-10 font-bold text-transparent bg-gradient-to-tl from-blue-600 to-cyan-400 bg-clip-text">Welcome back</h3>
                                    <p class="mb-0">Enter your username and password to sign in</p>
                                </div>
                                <div class="flex-auto p-6">
                                    @if ($errors->any())
                                        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-3" role="alert">
                                            {{--<strong class="font-bold">Holy smokes!</strong>--}}
                                            <span class="block sm:inline">{{ $errors->first() }}</span>
                                            <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
                                                <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
                                            </span>
                                        </div>
                                    @endif
                                    <form role="form" method="post" action="{{ route('admin.login') }}">
                                        @csrf
                                        <label class="mb-2 ml-1 font-bold text-xs text-slate-700">Username</label>
                                        <div class="mb-4">
                                            <input type="text" name="username" value="{{ old('username') }}" class="focus:shadow-soft-primary-outline text-sm leading-5.6 ease-soft block w-full appearance-none rounded-lg border border-solid border-gray-300 bg-white bg-clip-padding px-3 py-2 font-normal text-gray-700 transition-all focus:border-fuchsia-300 focus:outline-none focus:transition-shadow" placeholder="Username" aria-label="Username" aria-describedby="email-addon" required />
                                        </div>
                                        <label class="mb-2 ml-1 font-bold text-xs text-slate-700">Password</label>
                                        <div class="mb-4">
                                            <input type="password" name="password" class="focus:shadow-soft-primary-outline text-sm leading-5.6 ease-soft block w-full appearance-none rounded-lg border border-solid border-gray-300 bg-white bg-clip-padding px-3 py-2 font-normal text-gray-700 transition-all focus:border-fuchsia-300 focus:outline-none focus:transition-shadow" placeholder="Password" aria-label="Password" aria-describedby="password-addon" required />
                                        </div>
                                        <div class="min-h-6 mb-0.5 block pl-12">
                                            <input id="rememberMe" name="remember" class="mt-0.54 rounded-10 duration-250 ease-soft-in-out after:rounded-circle after:shadow-soft-2xl after:duration-250 checked:after:translate-x-5.25 h-5 relative float-left -ml-12 w-10 cursor-pointer appearance-none border border-solid border-gray-200 bg-slate-800/10 bg-none bg-contain bg-left bg-no-repeat align-top transition-all after:absolute after:top-px after:h-4 after:w-4 after:translate-x-px after:bg-white after:content-[''] checked:border-slate-800/95 checked:bg-slate-800/95 checked:bg-none checked:bg-right" type="checkbox" {{ old('remember') ? 'checked' : '' }}/>
                                            <label class="mb-2 ml-1 font-normal cursor-pointer select-none text-sm text-slate-700" for="rememberMe">Remember me</label>
                                        </div>
                                        <div class="text-center">
                                            <button type="submit" class="inline-block w-full px-6 py-3 mt-6 mb-0 font-bold text-center text-white uppercase align-middle transition-all bg-transparent border-0 rounded-lg cursor-pointer shadow-soft-md bg-x-25 bg-150 leading-pro text-xs ease-soft-in tracking-tight-soft bg-gradient-to-tl from-blue-600 to-cyan-400 hover:scale-102 hover:shadow-soft-xs active:opacity-85">Sign in</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="w-full max-w-full px-3 lg:flex-0 shrink-0 md:w-6/12">
                            <div class="absolute top-0 hidden w-3/5 h-full -mr-32 overflow-hidden -skew-x-10 -right-40 rounded-bl-xl md:block">
                                <div class="absolute inset-x-0 top-0 z-0 h-full -ml-16 bg-cover skew-x-10" style="background-image: url('{{ asset('img/admin/curved-images/curved6.jpg') }}')"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
</body>
</html>

resources/views/admin/resume.blade.php
@extends('admin.layout.base')

@section('content')
    <div class="flex flex-wrap -mx-3" x-data="resumes">
        <div class="flex-none w-full max-w-full px-3">
            <div class="relative resume flex flex-col min-w-0 mt-6 mb-6 break-words bg-white border-0 border-transparent border-solid shadow-soft-xl rounded-2xl bg-clip-border">
                <div class="w-full px-6">
                    <div class="flex justify-between items-center mb-5">
                        <h3 class="text-xl font-bold my-6">Education</h3>
                        <button type="button" class="flex items-center font-semibold text-base">
                            <i class='bx bxs-plus-circle'></i> <span class="ml-1">Add Education</span>
                        </button>
                    </div>
                    <ul id="input-education-list" x-ref="inputEducationList" class="w-full pb-6">
                        <template x-for="(school, index) in resumes.school">
                            <div class="resume-item">
                                <div class="flex justify-between items-center">
                                    <h4 x-text="school.title"></h4>
                                    <div class="flex items-center">
                                        <button type="button" class="bg-blue-700 rounded w-8 h-8 mr-3"><i class='bx bxs-pencil text-white'></i></button>
                                        <button type="button" class="bg-red-500 rounded w-8 h-8"><i class='bx bxs-trash text-white'></i></button>
                                    </div>
                                </div>
                                <h5 x-text="school.start.split('-')[0] + ' - ' + (school.end ? school.end.split('-')[0] : 'Now')"></h5>
                                <p><em x-text="school.institution"></em></p>
                                <p x-html="school.description"></p>
                            </div>
                        </template>
                    </ul>
                </div>
            </div>

            <div class="relative resume flex flex-col min-w-0 mt-6 mb-6 break-words bg-white border-0 border-transparent border-solid shadow-soft-xl rounded-2xl bg-clip-border">
                <div class="w-full px-6">
                    <div class="flex justify-between items-center mb-5">
                        <h3 class="text-xl font-bold my-6">Work Experience</h3>
                        <button type="button" class="flex items-center font-semibold text-base">
                            <i class='bx bxs-plus-circle'></i> <span class="ml-1">Add Work Experience</span>
                        </button>
                    </div>
                    <ul id="input-education-list" x-ref="inputEducationList" class="w-full pb-6">
                        <template x-for="(work, index) in resumes.work">
                            <div class="resume-item">
                                <div class="flex justify-between items-center">
                                    <h4 x-text="work.title"></h4>
                                    <div class="flex items-center">
                                        <button type="button" class="bg-blue-700 rounded w-8 h-8 mr-3"><i class='bx bxs-pencil text-white'></i></button>
                                        <button type="button" class="bg-red-500 rounded w-8 h-8"><i class='bx bxs-trash text-white'></i></button>
                                    </div>
                                </div>
                                <h5 x-text="work.start.split('-')[0] + ' - ' + (work.end ? work.end.split('-')[0] : 'Now')"></h5>
                                <p><em x-text="work.institution"></em></p>
                                <p x-html="work.description"></p>
                            </div>
                        </template>
                    </ul>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        document.addEventListener('alpine:init', () => {
            Alpine.data('resumes', () => ({
                resumes: @json($resumes),
                addSkill() {
                    this.resumes.push({
                        name: null,
                        value: null
                    });
                },
                removeSkill(index) {
                    this.resumes.splice(index, 1);
                }
            }))
        })
    </script>
@endpush